### ISSUE TITLE
Questions about confidence score

### ISSUE THREAD

**Issue by liubo-chen** [WeitaiKang/SegVG#1]
The paper doesn't seem to mention how to convert confidence score to Focal loss factor. Is it that the lower the confidence the higher the Focal loss factor?

**Comment by WeitaiKang** [comment]
Correct. A lower confidence has a higher focal loss factor. 

It is just the common way to transfer the [Focal Loss](https://arxiv.org/pdf/1708.02002) factor, so we don't include the details. We will release the code for your comprehensive reference.

**Comment by yahooo-m** [comment]
When will the code released?

**Comment by WeitaiKang** [comment]
> When will the code released?

The code will be open-sourced soon, estimated within one to two months.
