### ISSUE TITLE
How large is the computation?

### ISSUE THREAD

**Issue by KevinfromTJ** [WeitaiKang/SegVG#2]
I wonder if you could share more details about the training cost (GPUs and days)

**Comment by WeitaiKang** [comment]
Sure,

For costs, I just compared GFLOPs and training time with VLTVG. I used 4*A6000 GPUs with the same environment to test the training time required to achieve the best performance on ReferItGame. Btw, I remember VLTVG has less cost than TransVG and QRNet. Results are as below. It is affordable I think.

| Model | GFLOPS (G) | Training Time |
|-------|------------|---------------|
| VLTVG | 69.87      | 16 hours      |
| SegVG | 73.48      | 28 hours      |
